default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    - id: flake8
      additional_dependencies:
      - flake8-bugbear
      - flake8-builtins
      - flake8-comprehensions
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
    - id: yesqa
      additional_dependencies:
      - flake8-bugbear
      - flake8-builtins
      - flake8-comprehensions
