repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      additional_dependencies:
      - flake8-bugbear
      - flake8-builtins
      - flake8-comprehensions
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black
  - repo: https://github.com/asottile/yesqa
    rev: 265e9ff7c83add4949f81bb5fe14f4a743ffb04c  # frozen: v1.4.0
    hooks:
    - id: yesqa
      additional_dependencies:
      - flake8-bugbear
      - flake8-builtins
      - flake8-comprehensions
